[window]
dimensions={columns=100, lines=25}
padding={x=3,y=3}

[font]
normal={family="JetBrainsMono Nerd Font", style="Regular"}
size=12

[terminal.shell]
program = "wsl.exe"
args = ["-d", "Ubuntu", "--cd", "~", "--", "zsh", "-l"]